# Merge a "patch branch"
name: 'Patch Git'
inputs:
  name:
    required: true
  local-dir:
    required: true
  main-repository:
    required: true
  patch-repository:
    required: true
  patch-branch:
    required: true
  patch-remote-name:
    required: true
  work-branch:
    required: true
runs:
  using: "composite"
  steps:
    - name: Apply ${{ inputs.name }} changes
      shell: bash
      env:
        MAIN_REPOSITORY: ${{ inputs.main-repository }}
        PATCH_REMOTE_NAME: ${{ inputs.patch-remote-name }}
        PATCH_REPOSITORY: ${{ inputs.patch-repository }}
        PATCH_BRANCH: ${{ inputs.patch-branch }}
        # Taken from a 'git fetch' from actions/checkout
        GIT_FETCH: -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules
        WORK_BRANCH: ${{ inputs.work-branch }}
      working-directory: ${{ inputs.local-dir }}
      run: |
        REFERENCE_BRANCH=$(git rev-parse --abbrev-ref HEAD)
        REFERENCE_COMMIT=$(git rev-parse HEAD)

        if [[ ${MAIN_REPOSITORY} != ${PATCH_REPOSITORY} ]] ; then
          echo "::group::Add remote ${PATCH_REPOSITORY}"
          git remote add ${PATCH_REMOTE_NAME} https://github.com/${PATCH_REPOSITORY}.git
          echo "::endgroup::"
        fi

        echo "::group::Fetch ${PATCH_BRANCH} from ${PATCH_REPOSITORY}"
        git ${GIT_FETCH} ${PATCH_REMOTE_NAME} +refs/heads/${PATCH_BRANCH}*:refs/remotes/${PATCH_REMOTE_NAME}/${PATCH_BRANCH}* +refs/tags/${PATCH_BRANCH}*:refs/tags/${PATCH_BRANCH}*
        echo "::endgroup::"

        echo "::group::Checkout branch ${PATCH_BRANCH} from ${PATCH_REPOSITORY}"
        git checkout --progress --force -B ${PATCH_BRANCH} refs/remotes/${PATCH_REMOTE_NAME}/${PATCH_BRANCH}
        PATCH_COMMIT=$(git rev-parse ${PATCH_BRANCH})
        echo "::endgroup::"

        echo "::group::Create new work branch ${WORK_BRANCH} from ${REFERENCE_BRANCH} at ${REFERENCE_COMMIT}"
        git checkout -b ${WORK_BRANCH} ${REFERENCE_COMMIT}
        echo "::endgroup::"

        echo "::group::Merge ${PATCH_BRANCH} into ${WORK_BRANCH}"
        git merge --no-edit ${PATCH_BRANCH}
        echo "::endgroup::"

        echo "## ${{ inputs.name }} changes" >> $GITHUB_STEP_SUMMARY
        echo "| Remote | Branch | Commit |" >> $GITHUB_STEP_SUMMARY
        echo "|--|--|--|" >> $GITHUB_STEP_SUMMARY
        echo "| ${PATCH_REPOSITORY} | ${PATCH_BRANCH} | ${PATCH_COMMIT} |" >> $GITHUB_STEP_SUMMARY
        echo "| ${MAIN_REPOSITORY} | ${REFERENCE_BRANCH} | ${REFERENCE_COMMIT} |" >> $GITHUB_STEP_SUMMARY
